images:
  go-app.development:
    image_version_arg_key: GO_VERSIONS
    versions:
      - version: "1.25.3"
        latest: true
    architectures:
      - platform: linux/amd64
        runner: ubuntu-24.04
      - platform: linux/arm64
        runner: ubuntu-24.04-arm
  node-webapp.development:
    image_version_arg_key: NODE_VERSION
    versions:
      - version: "22"
        latest: true
      - version: "20"
    architectures:
      - platform: linux/amd64
        runner: ubuntu-24.04
      - platform: linux/arm64
        runner: ubuntu-24.04-arm
