name: publish-the-container-image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      language-version-arg-key:
        description: "The programming language version build arg such as: NODE_VERSION"
        required: true
        type: string
      language-versions-csv:
        description: "The programming language versions such as: 18,20,22"
        required: true
        type: string

jobs:
  # ================================================================
  # Parse CSV formatted input values
  parse-csv-inputs:
    env:
      LANGUAGE_VERSIONS_CSV: null
    runs-on: ubuntu-latest
    outputs:
      language-versions-json: ${{ steps.set-outputs.outputs.language-versions-json }}
    steps:
      - id: set-outputs
        name: set-outputs
        run: |
          _QUOTED="\"$(echo ${{ inputs.language-versions-csv }} | sed 's/,/","/g')\""
          echo "language-versions-json=[${_QUOTED}]" >> $GITHUB_OUTPUT
  # ================================================================
  # Build images
  build-image:
    env:
      PLATFORM_PAIR: null
      REGISTRY_PREFIX: null
      TAG_SUFFIX: null
    needs:
      - parse-csv-inputs
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        language-version: ${{ fromJson(needs.parse-csv-inputs.outputs.language-versions-json) }}
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      #
      # Generate the docker tag prefix with the registry - ghcr.io
      - name: Generate tag prefix for ghcr.io
        run: |
          echo REGISTRY_PREFIX="ghcr.io/${{ github.repository_owner }}" >> $GITHUB_ENV
      #
      # Generate the docker tag suffix
      - name: Generate the docker tag suffix using the git tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo TAG_SUFFIX="${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Generate the docker tag suffix using the current date
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo TAG_SUFFIX="$(date +%Y%m-)${GITHUB_SHA::7}" >> $GITHUB_ENV
      #
      - uses: docker/setup-buildx-action@v3
      #
      # Build the images
      # See also:
      #   - https://docs.docker.com/reference/cli/docker/buildx/build/#output
      #   - https://docs.docker.com/reference/cli/docker/buildx/build/#platform
      #   - https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
      - name: Set Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_PREFIX }}/${{ inputs.image-name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image digest
        id: build-and-push-image
        uses: docker/build-push-action@v6
        with:
          build-args: ${{ inputs.language-version-arg-key }}=${{ matrix.language-version }}
          context: Dockerfile.d/${{ inputs.image-name }}/
          labels: ${{ steps.docker-metadata.outputs.labels }}
          platforms: ${{ matrix.platform }}
          provenance: false
          tags: ${{ env.REGISTRY_PREFIX }}/${{ inputs.image-name }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build-and-push-image.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Generate artifact name
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.runner }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1
  # ================================================================
  # Merge built images
  merge-images:
    env:
      REGISTRY_PREFIX: null
      TAG_SUFFIX: null
    needs:
      - parse-csv-inputs
      - build-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language-version: ${{ fromJson(needs.parse-csv-inputs.outputs.language-versions-json) }}
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_PREFIX }}/${{ inputs.image-name }}
          tags: |
            # Enable `latest` tag when the branch is default and the language version is first on versions list.
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && (inputs.language-versions-csv == matrix.language-version || startsWith(inputs.language-versions-csv, join(matrix.language-version, ','))) }}
            type=raw,value=${{ matrix.language-version }},enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=raw,value={{date 'YYYYMM'}}-{{sha}},enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
           $(printf '${{ env.REGISTRY_PREFIX }}/${{ inputs.image-name }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ env.REGISTRY_PREFIX }}/${{ inputs.image-name }}:${{ steps.docker-metadata.outputs.version }}
